### ISSUE TITLE
sometimes line breaks aren't saved in studio

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1074]
### Steps to Reproduce

1. Create a page
2. Add a table (with at least two rows)
3. In the first (non-header) cell, enter some text with line breaks, for example:
```
one

word

per

line
```
4. Enter the same text in the 2nd cell (in the same row).  Both cells should look the same now. 
5. Save the page
6. open it again

### Expected Behavior

- When the page is re-opened, both cells should _still_ look the same. 

### Actual Behavior

- in the first cell, the extra line breaks are removed. 
- If you publish this page as is, all the words will be run onto one line. 

### Screenshot or Screencast

https://user-images.githubusercontent.com/430126/156170821-15a69403-af1b-49a5-ba5c-943c369a94b5.mov

**Comment by alicewriteswrongs** [comment]
I figured out what's going on, there was something we added as part of our Markdown table support (w/ custom shortcodes) that transformed `\n\n` to `\n` on save - this was done in order to avoid an issue I was seeing before with text with leading `\n\n` in table cells being duplicated. Happily, I removed the substitution and that issue doesn't seem to be happening! So we must have changed something else which fixed it.

**Comment by alicewriteswrongs** [comment]
@gumaerc I'm interested in your thoughts on this. I experimented a bit with different line-break replacements and looked at how they render in Hugo, and I think there's a bit of a weird thing going on.

Basically, the issue relates to Hugo rendering empty paragraphs in some circumstances where the Markdown libraries (showdown and turndown) that we're using in Studio don't do so. For instance, the following markdown string:

```md
{{< tdopen >}}

line

break

{{< tdclose >}}{{< tdopen >}}

- and
- a
- list

{{< tdclose >}}
```

is transformed by Showdown (`md -> html`) into this:

```html
<td>
  <p>line</p>
  <p>break</p>
</td>
<td>
  <ul>
    <li>and</li>
    <li>a</li>
    <li>list</li>
  </ul>
</td>
```

which I think is _basically_ what we want - there is not anything weird inserted around the list, it's basically cleanly transformed into normal semantic HTML.

The problem with that is that when we go to render the same Markdown string in Hugo it ends up inserting extra blank paragraphs in, like this:

```html
<td>
  <p></p>
  <p>line</p>
  <p>break</p>
  <p></p>
</td>
<td>
  <p></p>
  <ul>
    <li>and</li>
    <li>a</li>
    <li>list</li>
  </ul>
  <p></p>
</td>
```

Note the extra empty `<p>` tags around `line\n\nbreak` and the empty tags before and after the `<ul>`. This leads to a bit of a weird display --- since our `<p>` tags have `margin-bottom: 1rem` the empty tags add whitespace.

So one idea for dealing with this might be do replace leading `\n\n` in the table contents with `\n`, but this leads to other problems - we still get some empty tags, but the HTML gets weirder. This markdown string:

```md
{{< tdopen >}}
line

line

line
{{< tdclose >}}{{< tdopen >}}
- list
- of
- things
{{< tdclose >}}
```

is rendered by Hugo to this HTML:

```html
<td>
  line
  <p></p>
  <p>line</p>
  <p>line</p>
</td>
<td>
  <p></p>
  <ul>
    <li>list</li>
    <li>of</li>
    <li>things</li>
  </ul>
</td>
```

which also renders somewhat strangely.

### possible solution

I don't see a great way to get Hugo to do exactly what we want here, but I think there is an easy workaround that would get rid of the weirdness @pdpinch that you noticed in CKEditor and also not cause any rendering / display issues with extra whitespace.

I think we should:

1. leave leading and trailing `\n\n` on table cell content by getting rid of the substitution that we currently do and
2. add some CSS in `ocw-hugo-themes` which targets `td > p:empty` to set `display: none`

Together this will mean that we have _predictable_ empty `<p>` tags around table cell content --- empty paragraphs will appear before and after `<ul>` tags for instance --- but we can eliminate any whitespace in the rendered content with the CSS rule.

@gumaerc I'm wondering in particular if you may know of another way we could address this, or if there's a better workaround we could do.
