### ISSUE TITLE
Revert specific github commits with a management command

### ISSUE THREAD

**Issue by mbertrand** [mitodl/ocw-studio#1100]
As a developer, I'd like to revert changes made to content by syncing specific commits from github back to the database.  This existing `sync_backend_to_db` command can probably be modified to do this.

#### Designs and Mockups
- Add `--commit <checksum>` option to `sync_backend_to_db`
- Add/modify functions to implement this functionality
- If specified, sync that commit back to the database
- Resync from database back to github

**Comment by alicewriteswrongs** [comment]
is this for a command to update a whole site or just one piece of content?

**Comment by alicewriteswrongs** [comment]
I was asking because the context in which we've discussed doing this sounds like it's been mostly reverting a specific mistaken edit on one piece of content, but if we're syncing to the DB the state for a website at a particular commit then we'd be actually also undoing all other edits which have happened since that commit. If those edits are fine we probably don't want to do that.

**Comment by mbertrand** [comment]
I plan to add options to make it possible to update the whole site at that commit or just a specific file (based on path):

--commit <commit sha>
--path <specific git path>

**Comment by alicewriteswrongs** [comment]
should we possibly add a 'are you sure?' type of step if the user of the command doesn't specify a path?

**Comment by mbertrand** [comment]
Sure, good idea
