### ISSUE TITLE
saving page with legacy quote shortcode introduces extra &nbsp;

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-studio#1106]
### Steps to Reproduce

 - Visit https://ocw-studio-rc.odl.mit.edu/sites/15-es718-global-health-innovation-delivering-targeted-advice-to-an-organization-in-the-field-spring-2015/type/page/edit/c87e4d59-ef5e-63b2-60f6-695d695de21b/
 - Save the page and publish

### Expected Behavior

The page looks as it does in CKEditor

### Actual Behavior

After publishing, the author in the quote sections has an extra literal `&nbsp;` in front of it

**Comment by abeglova** [comment]
This occurs because the original hugo has a leading space in the text in the quote shortcode. The original hugo quote is

{{< quote "It can be difficult for students to imagine what it’s like to live in rural India and not have a smartphone or a car." " —Dr. Anjali Sastry" >}}

instead of 

{{< quote "It can be difficult for students to imagine what it’s like to live in rural India and not have a smartphone or a car." "— Dr. Anjali Sastry" >}}

I think the editor adding a &nbsp; there is ok. I put up a pr to fix it by updating the quote shortcode in ocw-hugo-themes to markdownify it's inputs so the &nbsp is displayed as a space
