### ISSUE TITLE
Markdown editor fails to add new list items

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-studio#113]
### Steps to Reproduce

Go to `/markdown-editor`, and click on the text next to one of the list items. You should be able to bold text or make other changes. However when you press enter, it will create a second CKEditor window instead of adding a new `li` element

**Comment by aliceriot** [comment]
figured out the bug and came up with a fix, will open a PR shortly

basically, I should have thought through more the implications of adding a second rule for translating `li` tags - we really only want one! so I changed the code to modify the existing rule in-place instead of adding a new rule, and I think the issue goes away. :woman_facepalming:
