### ISSUE TITLE
Include more file types in add link widget

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1168]
We started imported a wide range of text file some time ago, in https://github.com/mitodl/ocw-data-parser/issues/169

Course authors would like to be able to link to these file types, but they don't appear in the add link widget. 

For example, in https://ocw-studio-rc.odl.mit.edu/sites/1-017-computing-and-data-analysis-for-environmental-applications-fall-2003/type/page/edit/dc1d597b-6acf-4e17-f390-0ffb0e32fdf5/ the user can't add a link to the file cdffit.m which does exist in the course (actually, it exists twice).

**Comment by ChristopherChudzicki** [comment]
@pdpinch I want to double check on the desired behavior here regarding "Link" and "Embed".  From slack yesterday:

>I was talking to Ferdi about [this issue] & he suggested just adding a tab for “Other.” Do you see any problems with that?

I said "No". And this is in fact easy to do. But I want to double check on the desired behavior around "Add link" and "Embed" because I seem to have misunderstood how "Embed" currently works (in the case of documents). 

Currently it seems:
1. Add Link: In all cases, this creates a link to the "container page".
2. Embed, images and videos: really "embeds" images and videos in the current page.
3. Embed --> Document: Creates a link which is a direct download. *In particular,"Embedding" a PDF files does not embed a PDF viewer, which is sort of what I was expecting based on the name.*

    Also, for some reason I thought "Document" meant specifically PDF. But it seems to include other filetypes, too. (See screenshot from RC below). 

**Question A:** Is (3) the correct / expected behavior?

**Question B:** If Yes, then I think it might make more sense to just add all files to the "Documents" tab rather than creating a new "Other" tab. They would be functionally the same. 

- Whereas for all resource types, "Link" creates a link to the container page (not a direct download). 

So 


 I guess it turns out I've never tried embedding a

**Comment by Ferdi** [comment]
I think we can only embed video/images.  Embed should not show on the rest.

**Comment by ChristopherChudzicki** [comment]
Cool. After talking with Peter, I am going to remove "Documents" from the Embed picker.
