### ISSUE TITLE
Some courses have the same learner_resource_type twice

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1258]
### Steps to Reproduce

See https://ocw.mit.edu/courses/8-421-atomic-and-optical-physics-i-spring-2014/pages/assignments/

or, in github, https://github.mit.edu/mitocwcontent/8.421-spring-2014/blob/dab1d5141355a74015b953a055e8c1cbd0aa6222/data/course.json#L36-L42

### Expected Behavior

- there shouldn't be duplicate values
- I don't think studio allows the user to add the same value twice, so this might have been caused by an import

### acceptance criteria

- [x] review existing data & scrub it
- [x] confirm whether studio prevents duplicates. If it doesn't, open an issue to fix it.

**Comment by ChristopherChudzicki** [comment]
@pdpinch 9 courses were affected (https://docs.google.com/spreadsheets/d/1YN5MOAdrz7sLR7KXuKEhW9OaX9jgZCMsgBlaEfY6mho/edit?usp=sharing) I fixed the data manually but have not republished yet.

Re
>  confirm whether studio prevents duplicates. If it doesn't, open an issue to fix it.
Studio prevents this on the frontend as your suspected.

BTW: Alice wrote a proposal a while ago to switch our YAML schemas from [Yamale](https://github.com/23andMe/Yamale) to JSON Schema. JSON Schema comes with all sorts of nice things since it's an actual standard, but one of the nice things is its [`uniqueItems`](https://json-schema.org/understanding-json-schema/reference/array.html#id13) keyword. _A cursory glance at the Yamale docs makes me think it does not have something similar, but I could be wrong._

_Alice's issue talks about other, probably better, reaons for switching, but... `uniqueItems` is neat._

**Comment by ChristopherChudzicki** [comment]
These have been republished.

At least in some cases, the duplicate seems to have come from import: https://github.mit.edu/mitocwcontent/20.010j-spring-2006/commit/9ac6fa29ee5a05f02970f9433403e4b5d0a43af7#diff-ab06583f32f98c3846d6f1508b3c3dccR58
