### ISSUE TITLE
Video: publish downloadable video to S3

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1283]
As a course author, when I upload a file to gdrive, I'd like a download version to be created as well as the YouTube version. 

As a user, I'd like to be able to download a version of every video file, at a reasonable size. 

As part of our video workflow, we are already transcoding video to a size & bitrate suitable for downloading, but isn't available to end users through the published site. 

#### Acceptance Criteria:

- [ ] When a video is transcoded, update the resource metadata with a suitable path to the downloadble version (similar to what we do with legacy data) 
- [ ] When a course is published to staging, move the downloadable video file to the staging bucket on S3
- [ ] When a course is published to production, move the downloadable video file to the staging bucket on S3
- [ ] Confirm that the download links in the render site function. 
- [ ] Provide some timing information about publishing. We expect that the first time a course with a lot of video is published, the sync to S3 step will take much longer. But we also expect that subsequent publishes will be much faster, as the video data has already been moved. 

#### Out of Scope

- We are not yet uploading these "downoadable" versions to [The Internet Archive](https://archive.org). We haven't decided yet that we will continue this practice.

**Comment by mbertrand** [comment]
>Users can already do that.

Only for legacy OCW sites that have videos on internet archive like [this one](https://ocw.mit.edu/courses/res-8-007-cosmic-origin-of-the-chemical-elements-fall-2019/pages/videos/episode10/).

Last year we talked about uploading videos to Internet Archive, and there are transcoded videos made for this purpose, but the archive upload functionality has not been implemented yet.

**Comment by mbertrand** [comment]
The metadata field that is used for video downloads is `archive_url` ([example](https://github.mit.edu/raw/mitocwcontent/res.8-007-fall-2019/main/content/resources/episode-10-telescopes-and-observing.md?token=AAACMKRF6CQNXUN2ASAXI53COPQNE)) 

Since we are not going to upload to internet archive now (and maybe never?), I will need to copy the 16x9 transcoded video to the same bucket location as other non-video files.  Then we can do one of two things:

a) Assign the new S3 path to the `archive_url` field in the metadata, even though it isn't coming from internet archive. 
b) Assign the new S3 path to the `file` field in the metadata, but this will require a change to the theme to look for the download url in `archive_url` first, then `file` if it is blank.

I'm inclined to go with option (a) because it doesn't require any changes to the hugo theme.  What do you think @gumaerc ?

@Ferdi @pdpinch at some point, should the transcode job definition be modified to omit the 4x3 output if we will never use it?

**Comment by gumaerc** [comment]
@mbertrand I think what we do here depends on if we actually don't intend to archive videos on internet archive anymore.  If we actually don't then I don't see any problem with using that field as realistically that copy of the video effectively will be the archive.  Either way, the theme change in this regard would be pretty minimal so I don't really have an opinion either way.

**Comment by mbertrand** [comment]
Thanks, I'm going to assign it to the `file` field then, and make a separate PR to update the theme, just in case we end up using internet archive again later.
