### ISSUE TITLE
studio config file should specify resource picker tabs by itself

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1419]
The underlying issue is an incomplete separation of concerns between Studio frontend and OCW configs... When you insert links / resources into markdown, there’s this picker dialog with tabs (below). What tabs show up is determined by the config. (So ocw-www and ocw-courses can show different tabs, for example).

<img width="711" alt="Screen Shot 2022-06-30 at 12 13 39 PM" src="https://user-images.githubusercontent.com/9010790/176726793-870f48f4-a5da-46df-a003-140ba58d524d.png">

But—as currently written—studio needs know the set of possible tabs. The possible tabs and labels are stored in studio here:  https://github.com/mitodl/ocw-studio/blob/f00c392adbd827ea9c68051ef61a406c881a9b82/static/js/components/widgets/ResourcePickerDialog.tsx#L52

And the original commit specified a tab `resource-list` that studio was not prepared to deal with https://github.com/mitodl/ocw-hugo-projects/commit/9fe2ed0bb5d057535339274cb83d39f052af0337#diff-4e28d8dc0f3e2776c95d55c22426e08abadbb81b90355b2d10de8772fb7fcde1R37

The tabIds are hard-coded content type values. It would be good if we avoided this hard-coding of "possible tab" content types all together, and config handled it all

_Originally posted by @ChristopherChudzicki in https://github.com/mitodl/ocw-hugo-projects/issues/206#issuecomment-1171415424_

**Comment by pt2302** [comment]
Per discussion with @Ferdi and @pdpinch, this is the current plan for this issue:
- Leave the current config files in `ocw-hugo-projects` unchanged.
- The frontend should handle "known" types with hardcoded values (resources) and for anything else, use the `label` property from the config file. For example,
```
  - category: Content
    folder: content/video_galleries
    label: "Video Gallery"
    name: video_gallery
```
and 
```
link:
   - video_gallery
```
would create a `TabSettings` object with the following properties:
```
     title: "Video Gallery" #from the label, as above
     id: "video_gallery" #from the name, as above
     contentType: "video_gallery" #from the name, as above
     resourcetype: null #default
     embeddable: false #default
     singleColumn: true #default
```     
- If there is no associated content type defined in the config file, ignore the name provided in the link field and don't create a tab in the ResourcePicker.

**Comment by pt2302** [comment]
For context as to the reasoning behind this, the config files should support creating new content types that will then also appear in the ResourcePicker. Currently, this requires an additional set of changes to be made manually in the frontend. The new plan will allow for the existing config files to support creating new content types and associated tabs in the ResourcePicker with reasonable defaults. Additional changes to a content type's settings (such as making a new content type embeddable) will still require manual updates to the frontend. Since creating new content types will likely not be very frequent for most users, it is reasonable to set these defaults for new content types so as to avoid adding unnecessary complexity to the config files.
