### ISSUE TITLE
null metadata returned from websites api

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-studio#308]
### Steps to Reproduce

Visit https://ocw-studio-rc.odl.mit.edu/api/websites/?type=course in an incognito window

### Expected Behavior

Courses without any metadata are not returned

### Actual Behavior

They are returned, and the resulting courses break the use of `home_course_cards.html` in `ocw-hugo-themes` as they have no metadata set

**Comment by mbertrand** [comment]
Part of the issue here is that imported OCW courses get a populated `Website.metadata` field, which is what's returned in the API url above.  But new courses in ocw-studio will have metadata as a separate `WebsiteContent` object of type `sitemetadata`, and their `Website.metadata` field is never populated.  There should be more consistency.  

When OCW sites are imported, a `WebsiteContent` of type `sitemetadata` should be created instead, and the `Website.metadata` field should be removed.  The serializer used in the API query could then return the contents of that `WebsiteContent` object as the website metadata, and exclude any websites that don't have it.  

However, if the metadata objects for new websites don't have expected fields (and currently none do), then the API response would still break `home_course_cards.html` in `ocw-hugo-themes`.  This could be avoided by also filtering websites by the `WebsiteStarter` specific to OCW, _if_ that starter config accurately specified the content of the metadata (which again it currently does not).

The short term fix, which would eventually have to be reversed, is to filter the API results by `website.metadata__isnull=False`, which would limit the results to imported OCW sites.

**Comment by gumaerc** [comment]
@mbertrand What if we could add `website.metadata_isnull` as a filterable query string parameter, like `type`? This way, API queries that require metadata can intentionally filter out results that don't have it.

**Comment by mbertrand** [comment]
@gumaerc That would be the temporary quick fix, but longer term that `website.metadata` field should probably just go away because the metadata for all new sites are stored in a `WebsiteContent` object of type `sitemetadata`.  Currently, only imported OCW sites have a populated `metadata` field; that import process should be changed to store the metadata in a `WebsiteContent` object as well, but I don't think it's possible yet because we don't have the proper site config for it.

**Comment by mbertrand** [comment]
I'll make a PR for the bandaid approach but it will have to be reversed eventually.
