### ISSUE TITLE
Clicking away from forms in sidebar results in lost form state

### ISSUE THREAD

**Issue by gsidebo** [mitodl/ocw-studio#367]
For any form that is presented in the sidebar, if you edit some fields and click away to close that form, that data is lost (i.e.: the form is blank if you open it again). Desired behavior hasn't been decided yet.

**Comment by aliceriot** [comment]
yeah this is especially important I think because it's a bit easier to accidentally lose entered data than it would be if this form lived on it's own page. Right now you can close the drawer by just clicking outside of it or pressing escape - pretty easy for a user to do that by accident.

One idea for how to handle this could be to intercept that close action and pop up a confirmation if the form has been touched, asking 'Are you sure you want to close?' if the user has entered some data.

Another would be to just keep the data around somewhere and try to insert it whenever the form is re-opened. That raises some questions though - should this persist between refreshes, for instance? Github does this, and it's saved a long comment draft for me a couple of times!

**Comment by alicewriteswrongs** [comment]
I think this was addressed by #799
