### ISSUE TITLE
Evaluate CKEditor and produce live example

### ISSUE THREAD

**Issue by gsidebo** [mitodl/ocw-studio#39]
We use CKEditor as our WYSIWYG editor in Open. We want to evaluate this library to see if it's suitable for OCW Studio. 

Goals:
- Make sure we can have editable hugo shortcodes that editor understands
- Make sure we can support embedded youtube links (et al)
- Make sure that the editor can be initialized with markdown content and display it correctly

It may be helpful to evaluate this by using content from a `Website` that has been imported from our actual OCW courses (the `backpopulate_ocw_courses` command can be used). We know that course content has hugo shortcodes et. al.

**Acceptance criteria:**
- Comment on this issue with a 👍 /👎   for the viability of CKEditor for our OCW Studio use cases and the goals described above
- If 👍 , PR created that satisfies the following:
  - npm dependency added for CKEditor
  - Any relevant tooling added (editor tools for adding shortcodes, youtube links, etc)
  - Instructions included in the PR to render an editor and use those tools
- If 👎 , another issue(s) created to evaluate other WYSIWYG libraries

**Comment by gumaerc** [comment]
Something we're going to want to support here are custom buttons for adding [Hugo Shortcodes](https://gohugo.io/templates/shortcode-templates/).  They're basically like template blocks that can be embedded in Markdown like:

```md
These video lectures of Professor Gilbert Strang teaching 18.06 were recorded live in the Fall of 1999. Support for the video production was provided by the Lord Foundation of Massachusetts under a grant to the MIT Center for Advanced Educational Services.

{{< video-gallery-item href="/courses/18-06-linear-algebra-spring-2010/sections/video-lectures/lecture-1-the-geometry-of-linear-equations" section="Video Lectures" title="Lecture 1: The geometry of linear equations" description="These  video lectures of Professor Gilbert Strang teaching 18.06 were recorded  in Fall 1999 and do not correspond precisely to the current   edition  of the textbook. However, this book is  still the best  reference  for  more information on the topics covered in  each lecture. Strang, Gilbert. Introduction to Linear Algebra. 5th ed. Wellesley-Cambridge Press, 2016. ISBN: 9780980232776. Instructor/speaker: Prof. Gilbert Strang" thumbnail="https://img.youtube.com/vi/J7DzL2_Na80/default.jpg" >}}
```

So ideally there would be buttons for things like "Insert Video Gallery Item" that would take the different parameters defined here (`href`, `description`, `thumbnail`) and write out the shortcode based on a template.

**Comment by aliceriot** [comment]
alright, so I've gotten the basic editor running into a sort of trial / evaluation page where I can type in the editor and see the markdown that it outputs, like this:

![Screenshot from 2021-02-05 12-43-24](https://user-images.githubusercontent.com/6207644/107069599-2e158780-67b0-11eb-8326-cbe5c7b9c99d.png)

overall so far it is a bit of a pain to set up but it is working. some basic notes:

- I was able to re-use a little bit of code that we wrote for open-discussions (basically just the react component wrapper that we had there, which I rewrote as a functional component)
- the build is a bit finicky, so I had to add some webpack config to somewhat segregate ckeditor stuff from our code
- typescript support is nonexistent, more or less, but we can type our wrapper component and the plugin code that we write
- haven't yet really investigated how it will go to add shortcode support. I think I'll have to extend the ckeditor schema for that to work correctly.

**Comment by aliceriot** [comment]
the branch for what I've done so far is pushed up here: https://github.com/mitodl/ocw-studio/compare/ap/ckeditor

**Comment by aliceriot** [comment]
just went through some documentation relating to the [editor schema](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html) and followed a [tutorial for writing a simple plugin](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-a-block-widget.html).

The tutorial is for implementing a 'block widget', which is basically a new node-type that exists at the top level of the document (i.e. not nested within another block like a paragraph or something). Overall the basic steps for doing so look like:

- adding a new element type to the schema for the block type we want to define, by giving it a name, specifying where in the document it may be inserted, what it can contain, and things like that
- defining how that element should be represented in the editing UI within the editor
- adding some toolbar UI and some 'commands' for inserting a node of this type to the document.

overall, this isn't too complicated I think and is more or less similar to how other schema-based editors like prosemirror work.

then after adding a new type of node, defining how it should be rendered in the editing view, and so on, the next thing is the markdown serialization. unfortunately, the [markdown plugin](https://github.com/ckeditor/ckeditor5/tree/master/packages/ckeditor5-markdown-gfm) does not have support for customizing the markdown serialization and deserialization (meaning how it converts markdown -> CKEditor internal state and editor state -> markdown).

So, for instance, when I followed the above tutorial to add a sort of example 'block' level element to the document the markdown serializers basically converted an `<h1>` element that it contained to markdown (`# text`) but didn't do anything with the block itself. The Markdown plugin also doesn't have any configuration options, so if we wanted to go this route I think we would need to maintain our own fork of it in order to add support for serializing and deserializing our youtube embeds, for instance.

This is because ckeditor's markdown support is not, I guess you could call it, "schema aware," i.e. the markdown support isn't based on taking in a user-configurable schema and then generating a markdown parser and serializer from that (like, for instance, [prosemirror's markdown support](https://github.com/ProseMirror/prosemirror-markdown) is). So to support our schema we'd need to fork and maintain our own code. It looks like CKEditor is using the [marked](https://github.com/markedjs/marked) package for this, which looks [extensible](https://marked.js.org/using_pro), but we would need to basically have our schema / note type definitions be set up in multiple places (i.e. in the actual classes we write to define these things for the CKEditor internal state and then separately to support them in our custom markdown processor). So this is kind of unfortunate I think.

Some info on the size of the editor:

on my branch above:

```
total 7.1M
drwxr-xr-x 3 alice alice 4.0K Feb  8 12:08 ./
drwxr-xr-x 6 alice alice 4.0K Feb  4 09:05 ../
-rw-r--r-- 1 alice alice 1.1M Feb  8 12:08 root-c8946d4dfc52b752715a.js
-rw-r--r-- 1 alice alice 6.0M Feb  8 12:08 root-c8946d4dfc52b752715a.js.map
-rw-r--r-- 1 alice alice 1.1K Feb  8 12:08 style-56be7d2f43aedd85143b.js
-rw-r--r-- 1 alice alice 4.8K Feb  8 12:08 style-56be7d2f43aedd85143b.js.map
-rw-r--r-- 1 alice alice  116 Feb  8 12:08 style-8b1768a2294929f68839.css
-rw-r--r-- 1 alice alice  261 Feb  8 12:08 style-8b1768a2294929f68839.css.map
drwxr-xr-x 2 alice alice 4.0K Feb  8 12:08 translations/
```

vs on master:

```
total 1.7M
drwxr-xr-x 2 alice alice 4.0K Feb  8 12:10 ./
drwxr-xr-x 6 alice alice 4.0K Feb  4 09:05 ../
-rw-r--r-- 1 alice alice 339K Feb  8 12:10 root-04e39b23c9377731a634.js
-rw-r--r-- 1 alice alice 1.4M Feb  8 12:10 root-04e39b23c9377731a634.js.map
-rw-r--r-- 1 alice alice  116 Feb  8 12:10 style-8b1768a2294929f68839.css
-rw-r--r-- 1 alice alice  261 Feb  8 12:10 style-8b1768a2294929f68839.css.map
-rw-r--r-- 1 alice alice 1.1K Feb  8 12:10 style-95e2f82bc084dfafd842.js
-rw-r--r-- 1 alice alice 4.8K Feb  8 12:10 style-95e2f82bc084dfafd842.js.map
```

Anyhow, my thoughts so far on CKEditor for this use case:

### The good

- comes with a nicely built-out UI that supports a lot of different rich-text features out of the box
- extensible, schema-based editing core that can allow us to define the custom node types we need to support (i.e. video embeds, course content links, etc) with the ability to support rich editing (i.e. inline editing of an image caption or something)
- relatively easy markdown support
- plays fairly well with react (attaching to a DOM node via a `ref`)

### The bad

- build setup is complicated and doesn't feel very 'solid': subjective term I know, but there were several undocumented 'quirks' of the build process I had to work around in setting it up, some of which I had to basically use a hacky approach to fix, check out the webpack config changes on my branch to see.
- although markdown support is there, the authors of the editor seem to discourage relying on it, saying _"This_ feature is experimental. While the CKEditor 5 architecture supports changing the data format, in most scenarios we do recommend sticking to the default format which is HTML (supported by the HtmlDataProcessor). HTML remains the best standard for rich-text data."_ (here: https://ckeditor.com/docs/ckeditor5/latest/features/markdown.html#the-markdown-data-processor)
- not built with typescript, community-supplied types aren't usable (so the whole library is typed as `any`)
- it's kind of big. See the size comparison above, but on `master` our very minimal app (which has almost nothing in it) is 337kb, just adding a very basic version of the editor brings it up to 1.1mb. This probably isn't so much of a concern for us since this is mainly a tool to be used at work.

### The ugly

- markdown support is not extensible or 'schema aware,' so in addition to defining our custom nodes for the editor itself we would need to fork and maintain our own version of `@ckeditor/ckeditor5-markdown-gfm`

Right now I'm thinking that given the inflexibility of the markdown support it makes sense to take a look at some other editors as well. Interested in what @noisecapella @gumaerc @gsidebo @Ferdi @pdpinch think about all this.

**Comment by aliceriot** [comment]
Some possible other editors to consider:

- prosemirror: https://prosemirror.net/
- Remirror: an editor framework built w/ prosemirror + react: https://remirror.io/
- draft.js: react-based editor framework from facebook: https://draftjs.org/

possibly others? there is also quill.js https://quilljs.com/ and a few others.

**Comment by aliceriot** [comment]
also going to check out [slate.js](https://docs.slatejs.org/) and look to see how easy it is to use some of the code here: https://github.com/sharadcodes/hugo-shortcodes-netlify-cms

**Comment by gsidebo** [comment]
Don't know if this is relevant or if it has already been solved, but I'm pretty sure we need to make sure that we have the ability to support internal links, i.e.: links to other pages that the user has authored.

**Comment by aliceriot** [comment]
@gsidebo yeah, basically the last few days I've been working out how to support custom node types in CKEditor, which will let us support something like that. I started with implementing an embedded youtube video:

![Screenshot from 2021-02-11 16-28-24](https://user-images.githubusercontent.com/6207644/107702644-8d7c0780-6c88-11eb-84e8-b8238e7ac688.png)

So yeah that's working. Ferdi asked me to write some notes about a few questions:

## how do you add a button in the toolbar ?

For this we need to define a 'command', which is basically just a class that extends a class provided by CKEditor called `Command` which defines a `.execute` method. We can then write a 'ui plugin' which adds a bar icon and wires up that command to it.

You can see an example of this code in the file for the `YoutubeEmbed` plugin, here: https://github.com/mitodl/ocw-studio/compare/ap/ckeditor#diff-e05cf25fd9f94d0ce7d57fcd28f8de4bd6d877b39d5e083eda397cad4ec4c88e

## How do you add the form?

Haven't done this part yet :sweat_smile: 

## How do you theme the ‘preview’?

It's pretty themable I think. We can style it with CSS, put classes on things, etc.

## how do you convert to markdown, and back to html on edit?

I'm using a markdown library called 'Showdown' for markdown -> html conversion. I picked it because it had good support for basic markdown syntax and, of the 3-4 libraries I looked it, it had the most ergonomic API for extending the markdown syntax.

You can see the code for supporting Hugo's youtube shortcode here: https://github.com/mitodl/ocw-studio/compare/ap/ckeditor#diff-7aaa82f6f2ea486fea3584fc2e159dac6b2764a44d48c31fa07928ae20f36f46R29

This module (`static/js/lib/markdown.ts`) exports two functions, `md2html` and `html2md`. These are then incorporated into a 'data processor' class, which I define in our `Markdown` plugin, here: https://github.com/mitodl/ocw-studio/compare/ap/ckeditor#diff-f354b044ad526e4b3552b5c3c3b3de28bd75408e351d7669b65ea8449ff303c2

A `DataProcessor` is basically just a class that, at a minimum, defines a `toView` and `toData` method. These two methods basically then just call our `md2html` and `html2md` methods.

Note that we *do not* directly convert from markdown to a CKEditor AST or something like that. Instead, CKEditor is pretty much designed for editing HTML, and that is really what it wants as input. So instead of converting markdown directly to CKEditor view nodes, we basically convert markdown into clean HTML, and then that HTML is converted into a CKEditor 'view' using CKEditor's including `HTMLDataProcessor`. Likewise, when we serialized to markdown (i.e. when the `onChange` function equivalent fires) we convert CKEditor's internal state to html, and then convert that html to markdown (using our `html2md` function, implemented with Turndown).

Anyhow, it's a bit confusing. But you can see how it works by reading the source for the Markdown plugin. I based the class there on how CKEditor's markdown plugin is built (see https://github.com/ckeditor/ckeditor5/tree/master/packages/ckeditor5-markdown-gfm).

**Comment by aliceriot** [comment]
- one thing to think about it how to programmatically modify which plugins are enabled, so that we can disable e.g. a few shortcodes which aren't supported on a given course theme

**Comment by aliceriot** [comment]
todo:

- [ ] write up a brief overview of how a plugin is added to the editor (which classes, what needs to be there, links to examples, etc)
- [ ] look into support for tables in CKEditor, GFM for Showdown.js
- [ ] look into how to test the editor and our custom plugins, write some basic tests

**Comment by aliceriot** [comment]
by the way, here is the issue on the repo for marked.js that I reference on the call: https://github.com/markedjs/marked/issues/1693

basically, it seems that it wasn't built with extending the syntax in mind, so while it's technically possible it's not at all easy to do (afaict we'd have to fork it and muck around in the parser and lexer to get it to do what we want).

this led me to take a look at other JS md -> html libraries out there, of which there are many (as you might imagine). I looked at

- [showdown.js](https://github.com/showdownjs/showdown/)
- [remarkable](https://github.com/jonschlinkert/remarkable)
- [markdown-it](https://github.com/markdown-it/markdown-it)

these three are all extensible, so I basically decided on which one to use based on which one had the simplest API for extending the syntax. Based on what I read and tried out with them I thought this was Showdown, which lets you add support for e.g. the youtube shortcode like this:

```js
import { Converter } from "showdown"

const YOUTUBE_SHORTCODE_REGEX = /{{< youtube "(\S+)" >}}/

function youtubeShortcodeExtension() {
  return [
    {
      type:    "lang",
      regex:   YOUTUBE_SHORTCODE_REGEX,
      replace: (s: string, match: string) =>
        `<section class="${YOUTUBE_EMBED_CLASS}">${match}</section>`
    }
  ]
}

const converter = new Converter({
  extensions: [youtubeShortcodeExtension]
})

export function md2html(md: string): string {
  return converter.makeHtml(md)
}
```

I thought that was pretty compact and powerful for what we need here. Definitely we could look at other options too, although there are so many markdown libraries that it's a little overwhelming.

**Comment by Ferdi** [comment]
@aliceriot thanks for the clarification . Unfortunately that makes it much harder to reuse the default ckeditor markdown plugin .

**Comment by aliceriot** [comment]
put up an initial PR for review, which just adds the basic, no-frills editor without Markdown support or any custom plugins.

**Comment by gsidebo** [comment]
I'd say this checks all the boxes now. Further CKEditor improvements and additions can be written up as separate issues
