### ISSUE TITLE
add rich UI to display inserted resources in CKEditor

### ISSUE THREAD

**Issue by alicewriteswrongs** [mitodl/ocw-studio#454]
- [x] #503
- [x] #504
- [ ] #505
- [x] #506

**Comment by pdpinch** [comment]
Feel free to split this into separate issues, for images, documents and video, if it makes sense.

**Comment by pdpinch** [comment]
... also website collections.

**Comment by aliceriot** [comment]
for collections we have this issue as well: https://github.com/mitodl/ocw-studio/issues/317

**Comment by aliceriot** [comment]
@pdpinch @Ferdi so there's a slight complication to our plans here which I think is probably worth discussing before we continue. It relates to the comment that @gumaerc made here: https://github.com/mitodl/ocw-studio/pull/475#discussion_r684404957

Basically, right now we have built a lot of these features out in a totally configurable way, so that, for instance, the UI doesn't expect that a site always has a 'page' or 'resource' content type. When selecting resources to embed via the UI I added in #475, there is actually configuration under the hood, on the Markdown widget, which tells it to fetch site content records of a given type and to display them for embedding there.

The problem we run into is that since this is a configurable feature we can't really assume that these records have particular fields, for instance `file_type`, since these fields are set in the site configuration and could be anything.

Anyhow, this was raised on the embed UI pr (#475) because there was a question of whether we want to include some UI which would provide more context to the user about the different resources (aka site content records) that they are seeing in the picker. Adding such a piece of UI, for instance switching on the `file_type` field to show a little icon for pdf, image, etc, depends on us either:

1. adding configuration where we state, in the site configuration, what field should be access to enrich the resource display or
1. writing some UI that assumes a given field is there on the site content type we want to embed (i.e. assuming that `file_type` is set on these objects). this could be hard-coded, or something which tests for this field's presence and falls back to not displaying anything if not present.

Anyhow, I think this is question about how much the implementation of this resource embed feature should be coupled with out standard course configuration, and how much it should be a more general, configurable feature. Wondering your thoughts on this and what direction we should take.

**Comment by pdpinch** [comment]
Is it possible to go ahead with option 2 and then add the configuration support later? 

Can I have my cake and eat it too? 

> adding configuration where we state, in the site configuration, what field should be access to enrich the resource display or
> writing some UI that assumes a given field is there on the site content type we want to embed (i.e. assuming that file_type is set on these objects). this could be hard-coded, or something which tests for this field's presence and falls back to not displaying anything if not present.

**Comment by aliceriot** [comment]
Definitely - I think something that tries for the field and then doesn't render anything if it's not present is probably the simplest option, so if that sounds alright to you then that's good by me!

**Comment by alicewriteswrongs** [comment]
@pdpinch @Ferdi am I correct in thinking we discussed not having an embed for PDFs and the like?

**Comment by pdpinch** [comment]
That’s right. I can’t see a good reason to embed a pdf, or any document resource.

**Comment by alicewriteswrongs** [comment]
ok cool, I'm going to go ahead and close then since we've implemented initial support for video and images already
