### ISSUE TITLE
Populate file_type when a file is uploaded

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-studio#508]
When a file is uploaded, we should update the resource to set `file_type` to the mime type of that file

**Comment by gumaerc** [comment]
@pdpinch and I had a discussion about this.  Really `filetype` should probably be called `resourcetype` and we need a mapping from that to the mime types provided by the legacy data as well as newly uploaded files.  We could probably accomplish this with a data template.

**Comment by noisecapella** [comment]
We decided to import `file_type` from plone as `resourcetype` to avoid confusion. `filetype` will then be created on import with the `Image`, `Video`, `Document`, and `Other` from the mime type which is stored in `resourcetype`

**Comment by gumaerc** [comment]
@noisecapella Really my suggestion above was that we might want to call the property `resourcetype` in `ocw-studio` instead of `filetype`.  My reasoning behind this was that we refer to the content we create representing files in `ocw-studio` "resources" so I thought it would make sense to follow suit and call the type `resourcetype`.  In the legacy data, I don't know why we wouldn't just call it `mimetype` because that's what it is.

**Comment by noisecapella** [comment]
Sorry I think I was confusing there. `resourcetype` would be the field storing `Image`, `Video`, etc, and I would leave `file_type` as the mime type, as it is right now.
