### ISSUE TITLE
Don't allow index or _index for a filename

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-studio#829]
As a user, I'd like to be able to upload files or create pages without worrying how it could affect the hugo build service. We should either reject or slugify filenames which could potentially cause problems when the content is created or imported

#### Acceptance Criteria:

- [ ] Files published should not be named `index.md` or `_index.md`

**Comment by mbertrand** [comment]
@gumaerc there seem to be lots of imported ocw pages that have a `filename` of `_index`, should they be named something else?

Example:
https://github.mit.edu/ocw-content-rc/1.011-spring-2011/blob/main/content/pages/projects/_index.md
https://ocw-draft-qa.global.ssl.fastly.net/courses/1-011-project-evaluation-spring-2011/pages/projects/

**Comment by gumaerc** [comment]
@mbertrand In this case, `ocw-to-hugo` is creating these files on purpose.  `_index.md` indicates an actual "index" page, so this is used when there is a parent with child content in a legacy course.  `index.md` is used to denote a folder that is a "page bundle."  This means that the folder represents a single page, but you can put other things in there like static resources, etc. that can be associated with the page.  Basically, the goal here is to make sure that `ocw-studio` doesn't do this when it's not intentional, i.e. a user sets "Index" as the literal title of the page which would result in an `index.md` at the root.  If this were to happen, Hugo would interpret the entire root as a page bundle and none of the other pages would be rendered.  More info on this here: https://gohugo.io/content-management/organization/
