### ISSUE TITLE
CKeditor is not displaying some markdown text

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#894]
### Steps to Reproduce

Compare:
- The assignments page at https://ocw-studio-rc.odl.mit.edu/sites/24-200-ancient-philosophy-fall-2004/type/page/ 
- https://github.mit.edu/ocw-content-rc/24.200-fall-2004/blame/main/content/pages/assignments.md#L101-L107

### Expected Behavior

All the text in the markdown content should display (even if the rendering is messed up)

### Actual Behavior

The lines noted in the blame link appear to be missing in ckeditor. 

### Related Issues

Note that there are lot of markdown issues with this page, with the start and end of italicized text. 

### Screenshot or Screencast

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/430126/148578952-ecf8025e-5c71-4cba-9ff4-1cc0e77531c1.png">

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/430126/148578991-a06c2ebe-ddec-4117-a1d5-2411645c7753.png">

**Comment by alicewriteswrongs** [comment]
I'm not sure exactly what's going on here, it will require some investigation, but my guess would be something to do with line-breaks within the list items and unclosed `_` characters

**Comment by alicewriteswrongs** [comment]
page on current ocw prod for reference: https://ocw.mit.edu/courses/linguistics-and-philosophy/24-200-ancient-philosophy-fall-2004/assignments/

**Comment by ChristopherChudzicki** [comment]
@pdpinch After talking with @alicewriteswrongs and @gumaerc we think it makes sense to handle this in ocw-to-hugo.

### More info

The issue with `24-200-ancient-philosophy-fall-2004` is that the markdown contains unescaped angle brackets, for example:

```
aardvark <a beaver> and a cat

1. dog elephant
2. frog <a goat> hippo 
````

The `<a beaver>` etc is getting interpreted as unclosed anchor tags, and CKEditor is losing the stuff between them.

**Question**: Ca this be created in OCW Studio?
**Answer** No. If you try to create this data in OCW Studio the opening angle bracket `<` is escaped. The closing angle bracket is not escaped, but that seems to be OK.

So, since this only happens with migrated courses, ocw-to-hugo seems like the place to handle it.

**Comment by ChristopherChudzicki** [comment]
The screenshot in original post shows two issues: (1) missing text and (2) bad formatting.

The missing text is specific to migrated courses and should be fixed by https://github.com/mitodl/ocw-to-hugo/pull/438 . The bad formatting is a different issue, described in #935
