### ISSUE TITLE
import_ocw_course_sites improperly sets publish_date

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-studio#916]
In `ocw-to-hugo`, the `publishdate` value in the course metadata is sourced from the `first_published_to_production` value from the original OCW source data.  This value is currently being set on `publish_date` on the `Website` object created during runs of `import_ocw_course_sites`.  This isn't desired, as `publish_date` is supposed to reflect when the given site was last published live by Concourse.

Instead of setting `publish_date` on import, we should:

 - Add a new nullable field on `Website` objects called `first_published_to_production`
 - During import, populate `first_published_to_production` with the `publishdate` value from the `ocw-to-hugo` course metadata
 - On first publish of courses in `ocw-studio`, if `first_published_to_production` is null, set it to the current date
 - Set `publish_date` on `Website` objects every time a site is published live

**Comment by alicewriteswrongs** [comment]
should we also null out `publish_date` for already imported courses?

**Comment by gumaerc** [comment]
@alicewriteswrongs Yep, we should do that.  It should get re-populated the next time we run a mass publish.

**Comment by alicewriteswrongs** [comment]
ok cool, I'll add that to the migration

**Comment by alicewriteswrongs** [comment]
@gumaerc one other question for you (and possibly also for @mbertrand ). Reading through the code in `websites/api.py` I found the function `update_website_status`. It looks like right now it will update `publish_date` not when the status is set to `PUBLISH_STATUS_SUCCESS` but whenever it's in `PUBLISH_STATUS_FINAL`, meaning that it would currently be set even if a build errors out.

Do we want to change that behavior so that we only update `publish_date` on a successful publish? In the context of trying to have a way to filter on something like `website.has_this_thing_published_successfully_on_concourse()` I think this is the information we want to record - but not knowing too much about how the whole content sync pipeline works I don't want to change this willy-nilly, haha

**Comment by mbertrand** [comment]
I think it would be better to change the behavior so `publish_date` is only updated on a successful publish (ditto `draft_publish_date` for draft publishing).  There will still be `live_publish_status_updated_on` and `draft_publish_status_updated_on` to indicate when the last publish attempt was made, successful or not.
